### ISSUE TITLE
BS Compiler stuck

### ISSUE THREAD

**Issue by olenirwing** [rrdelaney/reason-scripts#80]
Whenever I make a change, the compiler compiles just as it should. However in around 70% of cases, the compiler get's stuck, and it just says Compiling... in the terminal.
I then have to stop the compiler and hit npm run again, and then the compiler works just fine for the first compilation, but then gets stuck again the first time or second time I recompile.

Side Notes: I already looked into filewatching via inotify and changed it to a higher amount.
I am using Ubuntu 18.04.01

**Comment by rrdelaney** [comment]
reason-scripts is no longer under active development. I'm not too sure about this issue, but it might be fixed by upgrading your bs-platform.
